name: banorte_intelligence
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_generative_ai: ^0.1.0  # Asegúrate de que esta versión exista en pub.dev
  intl: ^0.17.0  # Especifica una versión para intl
  animated_text_kit: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/Banorte_Intelligence.png
    - lib/assets/images/Banorte_Intelligence_red.png